Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BuscaAPI.Models {
    public class Consulta {

        public Endereco Root { get; set; }

    }
}

Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BuscaAPI.Models {
    public class Context : DbContext{

        public Context(DbContextOptions<Context> options) : base(options) { }

        public DbSet <Endereco> Enderecos { get; set; }
    }
}

Models/Endereco.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BuscaAPI.Models {

    [Table("Endereco")]
    public class Endereco {

        [Key]
        public int Idcep { get; set; }
        public string CEP { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
        public string UF { get; set; }

      
    }
}

Models/EnderecoCompleto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BuscaAPI.Models {

    public class EnderecoCompleto {
        public List<Endereco> ListaEndereco { get; set; }

    }
}

Controllers/ConsultaAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BuscaAPI.DAL;
using BuscaAPI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BuscaAPI.Controllers {
    [Route("api/Endereco")]
    [ApiController]
    public class ConsultaAPIController : ControllerBase {
        private readonly ConsultaDAO _consultaDAO;

        public ConsultaAPIController(ConsultaDAO consultaDAO) {

            _consultaDAO = consultaDAO;
        }


        // GET: /api/Endereco/ListarEnderecos
        [HttpGet]
        [Route("ListarEnderecos")]
        public IActionResult Listar() {
            return Ok(_consultaDAO.Listar());
        }

        // GET: /api/Endereco/ListarEndereco/81730-000
        [HttpGet]
        [Route("ListarEndereco/{cep}")]
        public IActionResult ListarPorCep([FromRoute] string cep) {
            Endereco e = _consultaDAO.BuscarPorCep(cep);
            if (e != null) {
                return Ok(e);
            }
            else {
                return NotFound(new { msg = "Cep não encontrado no banco" });
            }
        }

        // POST: /api/Endereco/CadastrarEndereco
        [HttpPost]
        [Route("CadastrarEndereco")]
        public IActionResult Cadastrar(Endereco endereco) {
            _consultaDAO.Cadastrar(endereco);
            return Created("", endereco);
        }

        // PUT: /api/Endereco/AlterarEndereco
        [HttpPut]
        [Route("AlterarEndereco")]
        public IActionResult Editar(Endereco endereco) {
            if (_consultaDAO.Editar(endereco)) {
                // pode retornar msg ou o objeto Endereco
                return Ok(new { msg = "Endereço editado com sucesso" });
                // return Ok(endereco);
            }
            return NotFound(new { msg = "Id do endereço não encontrado!" });
        }

        // DELETE: /api/Endereco/DeletarEndereco/2
        [HttpDelete]
        [Route("DeletarEndereco/{id}")]
        public IActionResult DeleteId([FromRoute] int id) {
            if (_consultaDAO.Excluir(id)) {
                return Ok(new { msg = "Endereço do id: " + id + " deletado com sucesso!" });
            }
            return NotFound(new { msg = "Id do endereço não encontrado!" });
        }

    }

}

Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using BuscaAPI.DAL;
using BuscaAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;


// Rafael Benedet Fernandes

namespace BuscaAPI.Controllers {
    public class ConsultaController : Controller {

        private readonly ConsultaDAO _consultaDAO;

        public ConsultaController(ConsultaDAO consultaDAO) {

            _consultaDAO = consultaDAO;
        }

        public IActionResult Index() {

            EnderecoCompleto ec = new EnderecoCompleto();
            ec.ListaEndereco = _consultaDAO.Listar();
            if (TempData["Endereco"] != null) {
                string resultado = TempData["Endereco"].ToString();
                Endereco endereco = JsonConvert.DeserializeObject<Endereco>(resultado);
                _consultaDAO.Cadastrar(endereco);
                ec.ListaEndereco = _consultaDAO.Listar();
            }
            return View(ec);
        }



        [HttpPost]
        public IActionResult ConsultaPorCEP(String txtCEP) {


            string url =
                $@"https://viacep.com.br/ws/{txtCEP}/json/";
            WebClient client = new WebClient();
            TempData["Endereco"] = client.DownloadString(url);
            return RedirectToAction("Index");
        }
    }
}

Views/Consulta/Index.cshtml
@model EnderecoCompleto


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Gerenciamento</title>
</head>
<body class="container" style="padding-top:30px">

    <div class="p-3 mb-2 bg-success text-white">Cadastro e Consulta ViaCEP</div>




    <div class="container form-inline" style="margin-top:30px">
        <form asp-action="ConsultaPorCEP" asp-controller="Consulta">
            <input type="text" id="txtCEP" class="form-control col-6" placeholder="Digite seu CEP" name="txtCEP" />
            <input type="submit" value="Cadastro e Consulta" class="btn btn-dark" />
        </form>
    </div>

    <div class="container" style="margin-top:30px"/>
    
    <br />

    <div>

        <table class="table table-striped table-dark">


            <thead>
                <tr>
                    <th scope="col">CEP</th>

                    <th scope="col">Logradouro</th>

                    <th scope="col">Complemento</th>

                    <th scope="col">Bairro</th>

                    <th scope="col">Localidade</th>

                    <th scope="col">UF</th>

                </tr>
            </thead>

            <tbody>

                @foreach (Endereco p in Model.ListaEndereco) {

                    <tr>
                        <td>
                            @p.CEP
                        </td>
                        <td>
                            @p.Logradouro
                        </td>
                        <td>
                            @p.Complemento
                        </td>
                        <td>
                            @p.Bairro
                        </td>
                        <td>
                            @p.Localidade
                        </td>
                        <td>
                            @p.UF
                        </td>
                    </tr>
                }
</table>
                


    </div>


</body>
</html>